[package]
name = "sled-mem-leak"
version = "0.1.0"
authors = ["Benjamin Heatwole <bheatwole@cwi-va.com>"]
edition = "2021"

[dependencies]
byteorder = "1.4"
procfs = "0.11"
rand = "0.8"
sled = "0.34"

[profile.release]
debug = 1